pluginManagement {
    repositories {
        gradlePluginPortal()
        google()
        mavenCentral()
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public' }
        maven { url 'https://repo.huaweicloud.com/repository/maven' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://jitpack.io/' }
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        maven { url 'https://jitpack.io/' }
        google()
        mavenCentral()
        maven { url 'https://mirrors.cloud.tencent.com/nexus/repository/maven-public' }
        maven { url 'https://repo.huaweicloud.com/repository/maven' }
        maven { url 'https://maven.aliyun.com/repository/public' }
    }
}
rootProject.name = "MaskWechat"
include ':app'
